### ISSUE TITLE
Does not compile from crates.io

### ISSUE THREAD

**Issue by smackysnacks** [schickling/rust-beanstalkd#4]
Rust version 1.16.0 stable. rust-beanstalkd 0.3.2 from crates.io fails to compile with errors mentioning `std::io::BufStream` is unresolved. This issue was fixed a few commits ago. Would you consider bumping the version and publishing it to crates.io?

**Comment by wezm** [comment]
@schickling I just updated [beanstalk-cli](https://github.com/schickling/beanstalkd-cli/pull/10) to work on stable rust. I used a git reference to this repo, which prevents publishing a new version of `beanstalk-cli` to crates.io. Any chance you could make a new release?

**Comment by schickling** [comment]
Can I add you as a collaborator and you take care of it @wezm? :)

**Comment by wezm** [comment]
Sure happy to take care of it. To be able to publish a new version of the crate I'll need be added as an [owner on crates.io](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner) (wezm is username there as well I think). To merge PRs in the repo I'll need to be a GitHub collaborator.

**Comment by schickling** [comment]
Done ✅

**Comment by wezm** [comment]
@schickling I have prepared a new release but I'm unable to publish it to crates.io (see error below). You will need to make me co-owner on crates.io (see link above) or publish the release yourself (`cargo publish` from the repo).

```
error: api errors: this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
```

**Comment by schickling** [comment]
I've added you as owner to the repo. Pls check your emails :)

**Comment by wezm** [comment]
Yes I can confirm that I have repo access. I need crates.io access to publish the release.

**Comment by wezm** [comment]
A new version has been published to crates.io that works on newer Rust versions.
